--https://school.programmers.co.kr/learn/courses/30/lessons/144856
--저자 별 카테고리 별 매출액 집계하기

SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
    INNER JOIN BOOK_SALES  S ON B.BOOK_ID = S.BOOK_ID
    INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC